### ISSUE TITLE
Create DNS CNAME for orlando.resists.org

### ISSUE THREAD

**Issue by rukh-ingress** [balshor/resists.org#10]
Please set up orlando.resists.org canonical name = rukh-ingress.github.io.

CNAME is set, but they're otherwise still thinking of the redirects they want.

**Comment by balshor** [comment]
Let me know when you have a redirect or other content available and I'll
set this up.

**Comment by rukh-ingress** [comment]
Thanks. Content has been added.

**Comment by balshor** [comment]
Added!

**Comment by rukh-ingress** [comment]
Thank you!
