### ISSUE TITLE
edinburgh.resists.org

### ISSUE THREAD

**Issue by rukh-ingress** [balshor/resists.org#16]
Please set up edinburgh.resists.org canonical name = rukh-ingress.github.io.

Open to discuss. Edinburgh is in the uk, for which CL uses craigslist.co.uk. But I don't care to dig into registering resists.co.uk and other international domains. Thoughts?

**Comment by balshor** [comment]
If they're happy with .org, I don't see a reason to grab an international TLD.

**Comment by rukh-ingress** [comment]
Thanks agreed.

Was the cname set up? Okay to close?
